//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEquipoVerde.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rec {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rec() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProyectoEquipoVerde.Recursos.Rec", typeof(Rec).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por fecha.
        /// </summary>
        internal static string btnBuscarFechaBusqueda {
            get {
                return ResourceManager.GetString("btnBuscarFechaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Imagen: .
        /// </summary>
        internal static string btnCargarImagenRegistro {
            get {
                return ResourceManager.GetString("btnCargarImagenRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PUNTÚA.
        /// </summary>
        internal static string btnCriticaPerfil {
            get {
                return ResourceManager.GetString("btnCriticaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR.
        /// </summary>
        internal static string btnEditarUsuario {
            get {
                return ResourceManager.GetString("btnEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR.
        /// </summary>
        internal static string btnEnviarCritica {
            get {
                return ResourceManager.GetString("btnEnviarCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INICIA SESIÓN.
        /// </summary>
        internal static string btnInicioSesionInicio {
            get {
                return ResourceManager.GetString("btnInicioSesionInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODIFICAR.
        /// </summary>
        internal static string btnModificarCritica {
            get {
                return ResourceManager.GetString("btnModificarCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGÍSTRATE.
        /// </summary>
        internal static string btnRegistrarseInicio {
            get {
                return ResourceManager.GetString("btnRegistrarseInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer visible.
        /// </summary>
        internal static string chbContrRegistro {
            get {
                return ResourceManager.GetString("chbContrRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string errorProvider1Inicio {
            get {
                return ResourceManager.GetString("errorProvider1Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio Sesión.
        /// </summary>
        internal static string InicioSesionLoginInfo {
            get {
                return ResourceManager.GetString("InicioSesionLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAG.
        /// </summary>
        internal static string label1PerfilPeli {
            get {
                return ResourceManager.GetString("label1PerfilPeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAG.
        /// </summary>
        internal static string label1Usuario {
            get {
                return ResourceManager.GetString("label1Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lblContrasenyaInicio {
            get {
                return ResourceManager.GetString("lblContrasenyaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña: .
        /// </summary>
        internal static string lblContrasenyRegistro {
            get {
                return ResourceManager.GetString("lblContrasenyRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crítica (opcional).
        /// </summary>
        internal static string lblCriticaCritica {
            get {
                return ResourceManager.GetString("lblCriticaCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRÍTICAS RECIENTES.
        /// </summary>
        internal static string lblCriticaRecientePerfil {
            get {
                return ResourceManager.GetString("lblCriticaRecientePerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CRÍTICAS RECIENTES.
        /// </summary>
        internal static string lblCriticaRecienteUsuario {
            get {
                return ResourceManager.GetString("lblCriticaRecienteUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string lblDescripcionPerfil {
            get {
                return ResourceManager.GetString("lblDescripcionPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Director: .
        /// </summary>
        internal static string lblDirecPerfil {
            get {
                return ResourceManager.GetString("lblDirecPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha:.
        /// </summary>
        internal static string lblFechaPerfil {
            get {
                return ResourceManager.GetString("lblFechaPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMG PERFIL.
        /// </summary>
        internal static string lblImagenPerfil {
            get {
                return ResourceManager.GetString("lblImagenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string lblNombreRegistro {
            get {
                return ResourceManager.GetString("lblNombreRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valoracion.
        /// </summary>
        internal static string lblNotaCritica {
            get {
                return ResourceManager.GetString("lblNotaCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PELÍCULAS.
        /// </summary>
        internal static string lblPelisBusqueda {
            get {
                return ResourceManager.GetString("lblPelisBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MEJOR VALORADAS.
        /// </summary>
        internal static string lblPelisMejorValoradasMain {
            get {
                return ResourceManager.GetString("lblPelisMejorValoradasMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PELÍCULAS VISTAS.
        /// </summary>
        internal static string lblPelisUsuario {
            get {
                return ResourceManager.GetString("lblPelisUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORTADA.
        /// </summary>
        internal static string lblPortadaBusqueda {
            get {
                return ResourceManager.GetString("lblPortadaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña:.
        /// </summary>
        internal static string lblRepetirContrasenyaRegistro {
            get {
                return ResourceManager.GetString("lblRepetirContrasenyaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAG.
        /// </summary>
        internal static string lblTagBusqueda {
            get {
                return ResourceManager.GetString("lblTagBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag.
        /// </summary>
        internal static string lblTagCritica {
            get {
                return ResourceManager.GetString("lblTagCritica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag.
        /// </summary>
        internal static string lblTagPerfil {
            get {
                return ResourceManager.GetString("lblTagPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título: .
        /// </summary>
        internal static string lblTitPerfil {
            get {
                return ResourceManager.GetString("lblTitPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string lblUsuarioInicio {
            get {
                return ResourceManager.GetString("lblUsuarioInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        internal static string lblUsuarioRegistro {
            get {
                return ResourceManager.GetString("lblUsuarioRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIOS MÁS ACTIVOS.
        /// </summary>
        internal static string lblUsuariosActivos {
            get {
                return ResourceManager.GetString("lblUsuariosActivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIOS.
        /// </summary>
        internal static string lblUsuariosBusqueda {
            get {
                return ResourceManager.GetString("lblUsuariosBusqueda", resourceCulture);
            }
        }
    }
}
